[package]
name = "vectrs"
version = "0.0.4"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
description = "A stack-allocated, constant-size, n-dimensional vector type"
readme = "README.md"
repository = "https://github.com/rossmacarthur/vectrs"
license = "MIT OR Apache-2.0"
keywords = ["math", "vector", "linear-algebra"]
categories = ["mathematics", "science", "no-std"]
include = ["benches/**/*", "src/**/*", "LICENSE-*", "README.md"]

[features]
default = ["std"]
std = []

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "main"
harness = false
