[package]
name = "vectrix"
version = "0.0.6"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
description = "A stack-allocated, constant-size, n-dimensional vector type"
readme = "README.md"
repository = "https://github.com/rossmacarthur/vectrix"
license = "MIT OR Apache-2.0"
keywords = ["math", "vector", "linear-algebra"]
categories = ["mathematics", "science", "no-std"]
include = ["benches/**/*", "src/**/*", "LICENSE-*", "README.md"]

[[bench]]
name = "main"
harness = false

[dependencies]
vectrix-macro = { path = "macro", optional = true }

[dev-dependencies]
criterion = "0.3.3"
rand = "0.8.0"

[features]
default = ["macro", "std"]
std = []
macro = ["vectrix-macro"]

[workspace]
members = ["macro"]
